package ch.zhaw.integration.beacons.utils;

public enum CalculationMethod {

    TRILATERATION_NO_SMOOTHING_LIBRARY_DISTANCE,
    TRILATERATION_NO_SMOOTHING_CALCULATED_DISTANCE,
    TRILATERATION_SLIDING_WINDOW_LIBRARY_DISTANCE,
    TRILATERATION_SLIDING_WINDOW_CALCULATED_DISTANCE,
    TRILATERATION_KALMANN_FILTER_LIBRARY_DISTANCE,
    TRILATERATION_KALMANN_FILTER_CALCULATED_DISTANCE,
    TRILATERATION_SLDING_WINDOW_AND_KALMANN_FILTER_LIBRARY_DISTANCE,
    TRILATERATION_SLDING_WINDOW_AND_KALMANN_FILTER_CALCULATED_DISTANCE;
}
